#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Start cron service
service cron start

python manage.py migrate
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'

