steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-f",
        "compose/production/django/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "tup-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--port"
      - "8000"
      - "--volume-mount"
      - "name=gs-tup,mount-path=/mnt/my-bucket"
      - "--volume"
      - "name=gs-tup,csi-driver=gcsfuse.run.googleapis.com,bucket-name=gs-tup"
