# Generated by Django 5.0.9 on 2024-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='anio_plan',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='materia',
            name='cuatrimestre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
