# Generated by Django 5.0.9 on 2024-10-09 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(help_text='Only Excel files (.xlsx, .xls) are allowed', upload_to='excels/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('last_reviewed', models.PositiveBigIntegerField(default=0)),
                ('excel_type', models.CharField(choices=[('sysacad', 'Sysacad'), ('sysadmin', 'Sysadmin')], default='sysacad', max_length=50)),
            ],
            options={
                'verbose_name': 'Excel',
                'verbose_name_plural': 'Excels',
            },
        ),
    ]
