# Generated by Django 5.0.9 on 2024-09-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='excel_type',
            field=models.CharField(choices=[('sysacad', 'Sysacad'), ('sysadmin', 'Sysadmin')], default='sysacad', max_length=50),
        ),
    ]
