# Generated by Django 5.0.9 on 2024-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_alter_excel_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='uploaded_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
