# Generated by Django 5.0.9 on 2024-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_excel_excel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='excel',
            name='last_reviewed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
