# Generated by Django 5.0.9 on 2024-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
