# Generated by Django 5.0.9 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='NonName', help_text='Full name of the user.', max_length=150, verbose_name='Full Name of User'),
        ),
    ]
