# Generated by Django 5.0.9 on 2024-10-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('ultimo_cursado', models.CharField(auto_created=True, choices=[('1C-2024', '1C-2024'), ('2C-2024', '2C-2024')], default='1C-2024')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado_financiero', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], default='Habilitado')),
                ('estado_academico', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo')),
                ('legajo', models.PositiveIntegerField(default=0, unique=True, verbose_name='Legajo')),
                ('anio_ingreso', models.IntegerField()),
                ('telefono', models.CharField(blank=True)),
                ('tel_res', models.CharField(blank=True)),
                ('celular', models.CharField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inhabilitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Rehabilitados',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], default='Rehabilitado')),
                ('fecha_rehabilitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_deshabilitacion', models.DateTimeField(null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumnos.alumno', to_field='legajo')),
            ],
        ),
    ]
