# Generated by Django 5.0.9 on 2024-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabilitacion',
            name='fecha_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
