# Generated by Django 5.0.9 on 2024-10-07 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehabilitados',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], default='Rehabilitado')),
                ('fecha_rehabilitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_deshabilitacion', models.DateTimeField(null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumnos.alumno', to_field='legajo')),
            ],
        ),
        migrations.DeleteModel(
            name='TipoEstado',
        ),
        migrations.RemoveField(
            model_name='inhabilitacion',
            name='id_tipo_inhabilitacion',
        ),
        migrations.DeleteModel(
            name='TipoInhabilitacion',
        ),
    ]
