# Generated by Django 5.0.9 on 2024-10-14 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_inhabilitacion_fecha_hasta'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosAInhabilitar',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_inhabilitacion', models.DateField()),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', to_field='legajo')),
            ],
        ),
    ]
