# Generated by Django 5.0.9 on 2024-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tel_res',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
