# Generated by Django 5.0.9 on 2024-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_delete_tipoestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabilitacion',
            name='fecha_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
