# Generated by Django 5.0.9 on 2024-10-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rehabilitados_delete_tipoestado_and_more'),
        ('alumnos', '0003_alter_inhabilitacion_fecha_hasta'),
    ]

    operations = [
    ]
