# Generated by Django 5.0.9 on 2024-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_tel_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tel_res',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, null=True),
        ),
    ]
