# Generated by Django 5.0.9 on 2024-09-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_celular_alter_alumno_tel_res_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumno_dni', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
