# Generated by Django 5.0.9 on 2024-09-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_remove_alumno_dni_alter_alumno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tel_res',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
