# Generated by Django 5.0.9 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_alumno_celular_alter_alumno_tel_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('0', 'Activo'), ('1', 'Inactivo'), ('2', 'Egresado'), ('3', 'Inhabilitado')], default='Activo'),
        ),
    ]
