#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${PGUSER}" ]; then
    base_PGimage_default_user='postgres'
    export PGUSER="${base_PGimage_default_user}"
fi
export DATABASE_URL="postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${PGDATABASE}",
            user="${PGUSER}",
            password="${PGPASSWORD}",
            host="${PGHOST}",
            port="${PGPORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
