# Generated by Django 5.1 on 2024-09-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_tipoinhabilitacion_id_tipo_inhabilitacion'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='recargo',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='tipo_puesto',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_vencimiento_1',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_vencimiento_2',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='compromisodepago',
            name='fecha_vencimiento_3',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_informado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
