# Generated by Django 5.0.9 on 2024-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_vencimiento_1',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_vencimiento_2',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_vencimiento_3',
            field=models.IntegerField(default=29),
        ),
    ]
