# Generated by Django 5.0.9 on 2024-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_confirmado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_informado',
            field=models.FloatField(default=0),
        ),
    ]
