# Generated by Django 5.0.9 on 2024-10-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('Impaga', 'Impaga'), ('Vencida', 'Vencida'), ('PagadaCompletamente', 'Pagada Completamente'), ('PagadaParcialmente', 'Pagada Parcialmente')], max_length=20),
        ),
    ]
