# Generated by Django 5.0.9 on 2024-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_compromisodepago_fecha_vencimiento_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodepago',
            name='fecha_vencimiento_3',
            field=models.IntegerField(default=28),
        ),
    ]
