# Generated by Django 5.0.9 on 2024-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_cuota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Informado', 'Informado'), ('Confirmado', 'Confirmado')], default='No Informado', max_length=100),
        ),
    ]
