# Generated by Django 5.0.9 on 2024-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_pago_descripcion_remove_pago_medio_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(blank=True, null=True),
        ),
    ]
