# Generated by Django 5.0.9 on 2024-10-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_monto_confirmado_alter_pago_comentario_and_more'),
        ('pagos', '0004_alter_pago_estado'),
    ]

    operations = [
    ]
