# Generated by Django 5.0.9 on 2024-09-21 07:17

import server.pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='ticket',
            field=models.ImageField(blank=True, null=True, upload_to=server.pagos.models.ticket_upload_to),
        ),
    ]
