# Generated by Django 5.0.9 on 2024-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_pago_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
