# Generated by Django 5.0.9 on 2024-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_pago_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
