# Generated by Django 5.0.9 on 2024-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_alter_pago_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nro_transferencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
