# Generated by Django 5.0.9 on 2024-09-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_pago_nro_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='id_cuota',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='nro_cuota',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
